# 工作流名称：构建并推送Docker镜像到GitHub Container Registry
name: 构建并推送Docker镜像

# 触发条件：推送到main分支、创建标签、手动触发
on:
  push:
    branches: [ main ]
    tags: [ 'v*' ]
  workflow_dispatch:

# 权限设置
permissions:
  contents: read
  packages: write

# 工作流任务
jobs:
  # 构建任务
  build:
    # 运行环境：最新版Ubuntu
    runs-on: ubuntu-latest
    
    # 任务步骤
    steps:
    # 步骤1：检出代码
    - name: 检出代码
      uses: actions/checkout@v4
      
    # 步骤2：设置Docker Buildx
    - name: 设置Docker Buildx
      uses: docker/setup-buildx-action@v3
      
    # 步骤3：登录到GitHub Container Registry
    - name: 登录到GitHub Container Registry
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
        
    # 步骤4：提取元数据（标签信息）
    - name: 提取元数据
      id: meta
      uses: docker/metadata-action@v5
      with:
        images: ghcr.io/${{ github.repository }}
        tags: |
          type=ref,event=branch
          type=ref,event=pr
          type=semver,pattern={{version}}
          type=semver,pattern={{major}}.{{minor}}
          latest
          
    # 步骤5：构建并推送Docker镜像
    - name: 构建并推送Docker镜像
      uses: docker/build-push-action@v5
      with:
        context: .
        platforms: linux/amd64  # 仅支持AMD x86架构
        push: true  # 推送到GHCR
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}
        cache-from: type=gha  # 使用GitHub Actions缓存
        cache-to: type=gha,mode=max  # 最大化缓存使用
        
    # 步骤6：输出镜像信息
    - name: 输出镜像信息
      run: |
        echo "🎉 Docker镜像已成功构建并推送到GitHub Container Registry!"
        echo "📦 镜像标签: ${{ steps.meta.outputs.tags }}"
        echo "🔗 拉取命令: docker pull ${{ steps.meta.outputs.tags }}"
        echo "🚀 运行命令: docker run -p 8501:8501 ${{ steps.meta.outputs.tags }}"
